<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>GasVentilation.DevHarness</AssemblyName>
    <RootNamespace>GasVentilation.DevHarness</RootNamespace>
    <OutputPath>..\..\tools\DevHarness\1.6\Assemblies\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" PrivateAssets="all" />
    <PackageReference Include="Lib.Harmony.Ref" Version="2.4.2" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GasVentilation\GasVentilation.csproj" Private="false" />
    <Reference Include="PipeSystem">
      <HintPath>$(VefDir)\1.6\Assemblies\PipeSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
